### ISSUE TITLE
Screen is kept alive/on even though option is turned off

### ISSUE THREAD

**Issue by Guy-Falkes** [home-assistant/companion.home-assistant#820] opened 2022-09-21 13:16 UTC
My Companion app on both android phone and android tablet keeps the screen alive/on even though i turned the option "keep screen on" off.
Running the latest versions of all (HA and companions apps).

**Comment by dshokouhi** [comment] 2022-09-21 13:34
Duplicate of https://github.com/home-assistant/android/issues/2881

**Closed** 2022-09-21 13:34 UTC
