### ISSUE TITLE
No way to complete HA onboarding on NVidia Shield

### ISSUE THREAD

**Issue by Bodge-IT** [home-assistant/companion.home-assistant#162] opened 2020-02-12 23:06 UTC
I get to the logon page and get stuck, cannot add username/pass or traverse fields to select trusted network user.

**Comment by dshokouhi** [comment] 2020-02-12 23:08
Duplicate of: https://github.com/home-assistant/home-assistant-android/issues/327

**Closed by dshokouhi** 2020-02-12 23:08 UTC
