### ISSUE TITLE
Feature request full screen for kiosk mode

### ISSUE THREAD

**Issue by sylviepipi** [home-assistant/companion.home-assistant#531] opened 2021-05-22 08:29 UTC
I would like to use home assistant companion as kiosk on an IPAD 
(tried other solution but they are way to slow based on fully kiosk browser/android). 

I'l be using browser_mod and external sensor to turn screen on/off.
however it seems there always is a top bar with time/wifi status/battery ...  

Possible to implement a  full screen mode option ?

**Comment by TomBrien** [comment] 2021-05-22 08:37
This is a duplicate of home-assistant/ios#405. This repository relates to the documentation only. Feature requests and issues with the apps should be in the iOS/android repositories as appropriate.

**Closed** 2021-05-22 08:37 UTC
