### ISSUE TITLE
On companion help page 'Requesting location updates' returns Page Not Found

### ISSUE THREAD

**Issue by drogfild** [home-assistant/companion.home-assistant#235] opened 2020-05-28 12:04 UTC
## The problem

Menu item 'Requesting location updates' links to page https://companion.home-assistant.io/docs/notifications/location-notification but it returns Page Not Found

![image](https://user-images.githubusercontent.com/35920772/83139089-7c886780-a0f4-11ea-885e-5f78f40e894e.png)

**Comment by TomBrien** [comment] 2020-05-28 14:43
This is a duplicate of #231 closing in favour of that

**Closed** 2020-05-28 14:43 UTC
Labels: duplicate
