### ISSUE TITLE
further tasker integration and support

### ISSUE THREAD

**Issue by pejotigrek** [home-assistant/companion.home-assistant#584] opened 2021-10-02 08:04 UTC
knowing that some options are used only/mostly at specific places or times, and that they sometimes can drain the battery, it would be great to have an opportunity to control them via tasker.

example: BLE transmitting sensor.

I've started to use that at home to control lights during evening (so time and location based) and noticed my phone battery goes down a little bit quicker than before. I'm also a tasker app user, so I automatically thought it would be nice to be able to turn off or change settings of each sensor via tasker profiles (when in/out location, while in sleep/awake mode etc). the said BLE sensor could be turned off when not in home, could be turned on but with smaller transmitting power at work etc. and while not all other sensors needs the same ability - having them visible and configurable in tasker would be a massive improvement.

**Comment by dshokouhi** [comment] 2021-10-02 08:37
Duplicate of https://github.com/home-assistant/android/issues/232

**Closed** 2021-10-02 08:37 UTC
