### ISSUE TITLE
Complications do not update on TTW (tilt to wake)

### ISSUE THREAD

**Issue by DaZeroXB** [home-assistant/companion.home-assistant#948] opened 2023-06-16 07:40 UTC
According to https://companion.home-assistant.io/docs/wear-os/ -> **Complications**:
 `The complications are updated automatically whenever the screen is turned on and roughly every 15 minutes. You can force a complication to update by tapping it on the watchface.`

However, this does not work in combination of **AOD + TTW**. When moving your wrist the display goes on but the complications won't update. With **AOD off** and **TTW on** it is working. If **AOD and TTW on** and you **tap** the display to wake it, it is also updating as expected.

Wearable: Google **Pixel Watch** (WearOS 3.5 / June '23 Update)

**Comment by jpelgrom** [comment] 2023-06-17 07:09
Closing as duplicate of home-assistant/android#3592

**Closed** 2023-06-17 07:09 UTC
